BangazonWorkforceSapphireElephants/Models/TrainingProgram.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace BangazonWorkforceSapphireElephants.Models
{
    public class TrainingProgram
    {
        public int Id { get; set; }

        [Required]
        [Display(Name = "Program")]
        public string Name { get; set; }        

        [Required(ErrorMessage = "Enter the start date and time.")]
        [Display(Name = "Start Date/Time")]        
        public DateTime StartDate { get; set; }          

        [Required(ErrorMessage = "Enter the end date and time.")]
        [Display(Name = "End Date/Time")]        
        public DateTime EndDate { get; set; }

        [Required(ErrorMessage = "Enter the maximum Attendees for this training.")]
        [Display(Name = "Max Attendees")]
        public int MaxAttendees { get; set; }

        public List<Employee> EmployeeList { get; set; }        
    }
}

BangazonWorkforceSapphireElephants/Controllers/TrainingProgramsController.cs
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Threading.Tasks;
using BangazonWorkforceSapphireElephants.Models;
using BangazonWorkforceSapphireElephants.Models.ViewModels;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;

namespace BangazonWorkforceSapphireElephants.Controllers
{
    public class TrainingProgramsController : Controller    
    {
        private readonly IConfiguration _configuration;

        public TrainingProgramsController(IConfiguration configuration)
        {
            this._configuration = configuration;
        }

        public SqlConnection Connection
        {
            get
            {
                return new SqlConnection(_configuration.GetConnectionString("DefaultConnection"));
            }
        }

        //      -- Created by CW
        //    ****************************************************************
        //                   GET: LIST of FUTURE Training Programs
        //    ****************************************************************

        public ActionResult Index()
        {
            using (SqlConnection conn = Connection)
            {
                conn.Open();
                using (SqlCommand cmd = conn.CreateCommand())
                {
                    cmd.CommandText = @"SELECT t.Id,
                                    t.[Name],
                                    t.StartDate,
                                    t.EndDate,
                                    t.MaxAttendees
                                FROM TrainingProgram t
                                WHERE EndDate > GETDATE()";

                    SqlDataReader reader = cmd.ExecuteReader();

                    List<TrainingProgram> futurePrograms = new List<TrainingProgram>();

                    while (reader.Read())
                    {
                        TrainingProgram futureProgram = new TrainingProgram
                        {
                            Id = reader.GetInt32(reader.GetOrdinal("Id")),
                            Name = reader.GetString(reader.GetOrdinal("Name")),
                            StartDate = reader.GetDateTime(reader.GetOrdinal("StartDate")),
                            EndDate = reader.GetDateTime(reader.GetOrdinal("EndDate")),
                            MaxAttendees = reader.GetInt32(reader.GetOrdinal("MaxAttendees"))
                        };

                        futurePrograms.Add(futureProgram);
                    }

                    reader.Close();
                    return View(futurePrograms);
                }
            }
        }

        //      -- Created by CW
        //    ****************************************************************
        //                   GET: LIST of PAST Training Programs
        //    ****************************************************************

        public ActionResult Past()
        {
            DateTime today = DateTime.UtcNow.AddDays(01);
            string filterDate = $"{today.Year}-{today.Month}-{today.Day}";

            using (SqlConnection conn = Connection)
            {
                conn.Open();
                using (SqlCommand cmd = conn.CreateCommand())
                {
                    cmd.CommandText = $@"SELECT Id, 
                                            [Name], 
                                            StartDate, 
                                            EndDate, 
                                            MaxAttendees
                                        FROM TrainingProgram
                                        WHERE EndDate < '{filterDate}'
                                        ORDER BY StartDate";
                    SqlDataReader reader = cmd.ExecuteReader();

                    List<TrainingProgram> pastPrograms = new List<TrainingProgram>();
                    while (reader.Read())
                    {
                        TrainingProgram pastProgram = new TrainingProgram
                        {
                            Id = reader.GetInt32(reader.GetOrdinal("Id")),
                            Name = reader.GetString(reader.GetOrdinal("Name")),
                            StartDate = reader.GetDateTime(reader.GetOrdinal("StartDate")),
                            EndDate = reader.GetDateTime(reader.GetOrdinal("EndDate")),
                            MaxAttendees = reader.GetInt32(reader.GetOrdinal("MaxAttendees"))
                        };

                        pastPrograms.Add(pastProgram);
                    }

                    reader.Close();
                    return View(pastPrograms);
                }
            }
        }

        //      -- Created by Anupama
        //    ****************************************************************
        //                   GET: Details---Training Programs
        //    ****************************************************************


        public ActionResult Details(int id)
        {
            using (SqlConnection conn = Connection)
            {
                conn.Open();
                using (SqlCommand cmd = conn.CreateCommand())
                {
                    cmd.CommandText = @"
            SELECT tp.Id as TrainingProgramId,
                tp.[Name],
                tp.StartDate,
                tp.EndDate,
                tp.MaxAttendees,
                e.Id as EmployeeId,
                e.FirstName,
                e.LastName,
                e.IsSupervisor,
                d.Id as DepartmentId
                
            FROM TrainingProgram tp
            
            left join EmployeeTraining et on tp.Id = et.TrainingProgramId
            left join Employee e on e.Id = et.EmployeeId
                    left join Department d on e.DepartmentId = d.Id
                    WHERE tp.Id = @Id";
                    cmd.Parameters.Add(new SqlParameter("@Id", id));
                    SqlDataReader reader = cmd.ExecuteReader(
                        );

                    TrainingProgram trainingProgram = null;

                    while (reader.Read())
                    {
                        if (trainingProgram == null)
                        {
                            trainingProgram = new TrainingProgram
                            {
                                Id = reader.GetInt32(reader.GetOrdinal("TrainingProgramId")),
                                Name = reader.GetString(reader.GetOrdinal("Name")),
                                StartDate = reader.GetDateTime(reader.GetOrdinal("StartDate")),
                                EndDate = reader.GetDateTime(reader.GetOrdinal("EndDate")),
                                MaxAttendees = reader.GetInt32(reader.GetOrdinal("MaxAttendees")),
                                EmployeeList = new List<Employee>()
                            };
                        }

                        if (!reader.IsDBNull(reader.GetOrdinal("EmployeeId")))
                        {


                            trainingProgram.EmployeeList.Add(
                                 new Employee
                                 {
                                     Id = reader.GetInt32(reader.GetOrdinal("EmployeeId")),
                                     FirstName = reader.GetString(reader.GetOrdinal("FirstName")),
                                     LastName = reader.GetString(reader.GetOrdinal("LastName")),
                                     IsSupervisor = reader.GetBoolean(reader.GetOrdinal("IsSupervisor")),
                                     DepartmentId = reader.GetInt32(reader.GetOrdinal("DepartmentId"))

                                 });

                        }


                    }

                    reader.Close();

                    return View(trainingProgram);

                }
            }
        }


        //      -- Created by CW
        //    *******************************************************
        //      GET: TrainingProgram View Model to Create a new One
        //    *******************************************************

        public ActionResult Create()
        {
            {
                TrainingProgramCreateViewModel viewModel = new TrainingProgramCreateViewModel();
                return View(viewModel);
            }
        }
        //      -- Created by CW
        //    ******************************************
        //          POST: The TrainingProgram Created
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(TrainingProgramCreateViewModel viewModel)
        {
            try
            {
                using (SqlConnection conn = Connection)
                {
                    conn.Open();
                    using (SqlCommand cmd = conn.CreateCommand())
                    {
                        cmd.CommandText = @"INSERT INTO TrainingProgram
                                    (Name, StartDate, EndDate, MaxAttendees)
                                    VALUES (@name, @startDate, @endDate, @maxAttendees)";
                        cmd.Parameters.Add(new SqlParameter("@name", viewModel.Name));
                        cmd.Parameters.Add(new SqlParameter("@startDate", viewModel.StartDate));
                        cmd.Parameters.Add(new SqlParameter("@endDate", viewModel.EndDate));
                        cmd.Parameters.Add(new SqlParameter("@maxAttendees", viewModel.MaxAttendees));

                        cmd.ExecuteNonQuery();

                        return RedirectToAction(nameof(Index));
                    }
                }
            }
            catch
            {
                return View(viewModel);
            }
        }

        //      -- Created by Anupama
        //    ****************************************************************
        //                   GET: TrainingPrograms/Edit

BangazonWorkforceSapphireElephants/Views/TrainingPrograms/Create.cshtml
@model BangazonWorkforceSapphireElephants.Models.ViewModels.TrainingProgramCreateViewModel

@{
    ViewData["Title"] = "Create";
}

<h2>Add a Training Program</h2>

@*<h4>TrainingProgramCreateViewModel</h4>*@
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StartDate" class="control-label"></label>
                <input asp-for="StartDate" class="form-control" />
                <span asp-validation-for="StartDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EndDate" class="control-label"></label>
                <input asp-for="EndDate" class="form-control" />
                <span asp-validation-for="EndDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MaxAttendees" class="control-label"></label>
                <input asp-for="MaxAttendees" class="form-control" />
                <span asp-validation-for="MaxAttendees" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

BangazonWorkforceSapphireElephants/Views/TrainingPrograms/Delete.cshtml
@model BangazonWorkforceSapphireElephants.Models.TrainingProgram

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this Training Program?</h3>
<div>
   <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StartDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EndDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EndDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MaxAttendees)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MaxAttendees)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

BangazonWorkforceSapphireElephants/Views/TrainingPrograms/Details.cshtml
@model BangazonWorkforceSapphireElephants.Models.TrainingProgram

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>TrainingProgram</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.StartDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.EndDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.EndDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.MaxAttendees)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.MaxAttendees)
        </dd>

          <h6> EmployeeName</h6><ol>
            @foreach (var item in Model.EmployeeList
               )
            {
                
                <li>
                     @Html.DisplayFor(model => item.FirstName) @Html.DisplayFor(model => item.LastName)
                </li>
            }
        </ol>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    <a asp-action="Index">Back to List</a>
</div>

BangazonWorkforceSapphireElephants/Views/TrainingPrograms/Edit.cshtml
@model BangazonWorkforceSapphireElephants.Models.ViewModels.TrainingProgramEditViewModel


@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Modify Training Programs</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="TrainingProgram.Id" class="control-label"></label>
                <input asp-for="TrainingProgram.Id" class="form-control" />
                <span asp-validation-for="TrainingProgram.Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TrainingProgram.Name" class="control-label"></label>
                <input asp-for="TrainingProgram.Name" class="form-control" />
                <span asp-validation-for="TrainingProgram.Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TrainingProgram.StartDate" class="control-label"></label>
                <input asp-for="TrainingProgram.StartDate" class="form-control" />
                <span asp-validation-for="TrainingProgram.StartDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TrainingProgram.EndDate" class="control-label"></label>
                <input asp-for="TrainingProgram.EndDate" class="form-control" />
                <span asp-validation-for="TrainingProgram.EndDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TrainingProgram.MaxAttendees" class="control-label"></label>
                <input asp-for="TrainingProgram.MaxAttendees" class="form-control" />
                <span asp-validation-for="TrainingProgram.MaxAttendees" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

BangazonWorkforceSapphireElephants/Views/TrainingPrograms/Index.cshtml
@model IEnumerable<BangazonWorkforceSapphireElephants.Models.TrainingProgram>

@{
    ViewData["Title"] = "Index";
}

<h2>Future Training Programs</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.StartDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EndDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.MaxAttendees)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Id)
                </td>
                <td>
                    @Html.ActionLink(($"{item.Name}"), "Details", new { id = item.Id })                    
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.StartDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.EndDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.MaxAttendees)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                    @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                </td>
            </tr>
        }
    </tbody>    
</table>
<p>
    <a asp-controller="TrainingPrograms" asp-action="Past">View Past Program</a>    
</p>

BangazonWorkforceSapphireElephants/Views/TrainingPrograms/Past.cshtml
@model IEnumerable<BangazonWorkforceSapphireElephants.Models.TrainingProgram>

@{
    ViewData["Title"] = "Past";
}

<h1>Past Trainings</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.StartDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EndDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.MaxAttendees)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.StartDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EndDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MaxAttendees)
            </td>
            <td>                
                @Html.ActionLink("Details", "Details", new { id=item.Id })                
            </td>
        </tr>
}
    </tbody>
</table>
<a asp-action="Index">Back to List</a>